SIGNAL_COLOUR = "deepskyblue"
GENERATED_SIGNAL_COLOUR = "red"
LATENT_SPACE_COLOUR = "grey"
DEFAULT_FONT_SIZE = 12
DEFAULT_FONT_FAMILY = "sans-serif"
DEFAULT_FONT = "Avenir"

SIGNAL_LIM_UPPER = 300 / 3.086e+22
SIGNAL_LIM_LOWER = -600 / 3.086e+22